name: Build and Deploy Prod to EC2

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Node Modules
        run: npm ci --force
      - name: Build and export
        run: |
          npm run build
          npm run export
        env:
          IP_STACK_API_KEY: ${{ secrets.IP_STACK_API_KEY }}
          NEXT_PUBLIC_STRAPI_URL: ${{ secrets.NEXT_PUBLIC_STRAPI_URL }}
      - name: Send changes to EC2 instance
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY_PROD }}
          REMOTE_HOST: ${{ secrets.HOST_PROD }}
          REMOTE_USER: ubuntu
          TARGET: /home/ubuntu
          SOURCE: out/
          SCRIPT_BEFORE: rm -rf ./*
